# -*- coding: utf-8 -*-

"""
   wegene.Models.GenotypesModel

   This file was automatically generated by APIMATIC BETA v2.0 on 02/22/2016
"""
from wegene.APIHelper import APIHelper
from wegene.Models.GenotypeModel import GenotypeModel

class GenotypesModel(object):

    """Implementation of the 'genotypes' model.

    An array of genotypes

    Attributes:
        genotypes (list of GenotypeModel): An array of genotypes

    """

    def __init__(self,
                 kwargs):
        """Constructor for the GenotypesModel class

        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    genotypes -- list of GenotypeModel -- Sets the attribute genotypes

        """
        self.data = list()
        for item in kwargs:
            self.data.append(GenotypeModel(**item))